#!/usr/bin/env bash

while IFS=: read -r user passwd uid gid home cmd; do
  printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" \
    "$user" "$gid" "$home" "$cmd" "$uid" "$passwd" "$user"
done </etc/passwd
