#!/usr/bin/env bash
# Listens on port 80.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default

sudo service nginx start

