#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the
#9th iteration, displays Best School and then Hi on a new line.
j=1
while [ $j -le 10 ]
do
	if [ $j -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
  j=$((j + 1))
done
